# Generated by Django 5.1.1 on 2024-10-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_1',
            field=models.CharField(default=1, help_text='Enter the phone number 1 of the user. For example: +994123456789.', max_length=50, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_2',
            field=models.CharField(default=1, help_text='Enter the phone number 2 of the user. For example: +994123456789.', max_length=50, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
