# Generated by Django 5.1.1 on 2024-10-13 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user_passport_id', models.CharField(help_text='Passport ID of the user for the payment history.', max_length=15, verbose_name='User Passport ID')),
                ('user_full_name', models.CharField(help_text='Full name of the user for the payment history.', max_length=255, verbose_name='User Full Name')),
                ('start_date', models.DateTimeField(help_text='The start date and time of the period for this payment history.', verbose_name='Start Date and Time')),
                ('end_date', models.DateTimeField(help_text='The end date and time of the period for this payment history.', verbose_name='End Date and Time')),
                ('hours_worked', models.PositiveIntegerField(help_text='The number of hours worked during the specified period.', verbose_name='Hours Worked')),
                ('hourly_rate', models.DecimalField(decimal_places=3, help_text='The hourly rate in AZN for this payment.', max_digits=10, verbose_name='Hourly Rate (AZN)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total payment amount for the hours worked.', max_digits=10, verbose_name='Total Price (AZN)')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('hours', models.PositiveIntegerField(help_text='The number of hours worked.', verbose_name='Hours')),
                ('price_per_hour', models.DecimalField(decimal_places=3, help_text='Price per hour in AZN, e.g. 0.001₼', max_digits=10, verbose_name='Price Per Hour (AZN)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price calculated based on hours * price per hour.', max_digits=10, verbose_name='Total Price (AZN)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
