# Generated by Django 5.1.1 on 2024-10-19 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('status', models.CharField(choices=[('in_calculation', 'In Calculation'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='in_calculation', help_text='Current status of the payment.', max_length=15, verbose_name='Status')),
                ('month', models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default='january', help_text='The month the payment is associated with.', max_length=15, verbose_name='Month')),
                ('user_passport_id', models.CharField(help_text='Passport ID of the user for the payment history.', max_length=15, verbose_name='User Passport ID')),
                ('user_full_name', models.CharField(help_text='Full name of the user for the payment history.', max_length=255, verbose_name='User Full Name')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total price calculated based on hours * price per hour.', max_digits=10, null=True, verbose_name='Total Price (AZN)')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, help_text='The number of hours worked.', max_digits=10, null=True, verbose_name='Hours')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('status', models.CharField(choices=[('in_calculation', 'In Calculation'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='in_calculation', help_text='Current status of the payment.', max_length=15, verbose_name='Status')),
                ('user_passport_id', models.CharField(help_text='Passport ID of the user for the payment history.', max_length=15, verbose_name='User Passport ID')),
                ('user_full_name', models.CharField(help_text='Full name of the user for the payment history.', max_length=255, verbose_name='User Full Name')),
                ('price_per_hour', models.DecimalField(decimal_places=3, help_text='Price per hour in AZN, e.g. 0.001₼', max_digits=10, verbose_name='Price Per Hour (AZN)')),
                ('end_date', models.DateTimeField(blank=True, help_text='The end date and time of the period for this payment history.', null=True, verbose_name='End Date and Time')),
            ],
            options={
                'verbose_name': 'User Payment',
                'verbose_name_plural': 'User Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
