# Generated by Django 5.1.1 on 2024-10-13 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 17, 2, 4, 662659, tzinfo=datetime.timezone.utc), help_text='The end date and time of the period for this payment history.', verbose_name='End Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 17, 2, 12, 749015, tzinfo=datetime.timezone.utc), help_text='The start date and time of the period for this payment history.', verbose_name='Start Date and Time'),
            preserve_default=False,
        ),
    ]
