# Generated by Django 5.1.1 on 2024-10-20 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='status',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('operator', 'Operator'), ('director', 'Director')], default=datetime.datetime(2024, 10, 20, 10, 12, 48, 993480, tzinfo=datetime.timezone.utc), help_text='Type of user (e.g., Student, Teacher, etc.) for this payment record.', max_length=20, verbose_name='User Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End date and time for the payment period.', null=True, verbose_name='End Date and Time'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=3, help_text='Hourly rate for the payment, in AZN. Example: 15.000₼.', max_digits=10, verbose_name='Price Per Hour (AZN)'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='user_full_name',
            field=models.CharField(help_text='Full name of the user for this payment record.', max_length=255, verbose_name='User Full Name'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='user_passport_id',
            field=models.CharField(help_text='Passport ID of the user for this payment record.', max_length=15, verbose_name='User Passport ID'),
        ),
    ]
