# Generated by Django 5.1.1 on 2024-10-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_userpayment_status_userpayment_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('director', 'Director')], help_text='Type of user (e.g., Student, Teacher, etc.) for this payment record.', max_length=20, verbose_name='User Type'),
        ),
    ]
