# Generated by Django 5.1.1 on 2024-10-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_end_date_payment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='The end date and time of the period for this payment history.', null=True, verbose_name='End Date and Time'),
        ),
    ]
