# Generated by Django 5.1.1 on 2024-10-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_usergroup_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_active',
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('paused', 'Paused'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('archived', 'Archived')], default='active', help_text='Current status of the group. It can be Active, Pending, Paused, Completed, Canceled, Expired, or Archived.', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('dropped_out', 'Dropped Out')], default='active', help_text="Current status of the student's participation. It can be Enrolled, Pending Enrollment, Graduated, Dropped Out, Suspended, Transferred, Inactive, Expelled, or Completed.", max_length=15, verbose_name='Status'),
        ),
    ]
