# Generated by Django 5.1.1 on 2024-11-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_remove_group_operator_group_mentor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='group',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='group',
            name='mentor_full_name',
            field=models.CharField(blank=True, help_text='The full name of the mentor.', max_length=150, null=True, verbose_name='Mentor Full Name'),
        ),
        migrations.AddField(
            model_name='group',
            name='mentor_passport_id',
            field=models.CharField(blank=True, help_text='The passport ID of the mentor.', max_length=20, null=True, verbose_name='Mentor Passport ID'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher_full_name',
            field=models.CharField(blank=True, help_text='The full name of the teacher.', max_length=150, null=True, verbose_name='Teacher Full Name'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher_passport_id',
            field=models.CharField(default='ctfgbh551', help_text='The passport ID of the teacher.', max_length=20, verbose_name='Teacher Passport ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='student_full_name',
            field=models.CharField(default='AAA BBB', help_text='The full name of the student.', max_length=150, verbose_name='Student Full Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='student_passport_id',
            field=models.CharField(default='WERrfgERFG', help_text='The passport ID of the student.', max_length=20, verbose_name='Student Passport ID'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(fields=('student_passport_id', 'group'), name='unique_student_passport_group'),
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='student',
        ),
    ]
