# Generated by Django 5.1.1 on 2024-11-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_usergroup_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_salary_for_teacher',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total salary paid to the teacher for this group.', max_digits=10, null=True, verbose_name='Group Salary for Teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='per_student_salary_for_teacher',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The salary paid to the teacher per student for this group.', max_digits=10, null=True, verbose_name='Per Student Salary for Teacher'),
        ),
    ]
