# Generated by Django 5.1.1 on 2024-10-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='name',
            field=models.CharField(help_text='Enter the name of the filial (branch).', max_length=255, unique=True, verbose_name='Filial Name'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='Enter the name of the program.', max_length=255, unique=True, verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(help_text='Enter a short, descriptive name for the purpose.', max_length=255, unique=True, verbose_name='Purpose Name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='Enter the name of the region.', max_length=255, unique=True, verbose_name='Region Name'),
        ),
        migrations.AlterField(
            model_name='sourceofinformation',
            name='name',
            field=models.CharField(help_text='Enter the name of the information source.', max_length=255, unique=True, verbose_name='Source Name'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(help_text='Enter the full name of the university.', max_length=255, unique=True, verbose_name='University Name'),
        ),
    ]
