# Generated by Django 5.1.1 on 2024-10-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_register_filial_alter_register_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('test', 'Test'), ('active', 'Active'), ('deactive', 'Deactive')], default='on_hold', help_text='Current status of the payment.', max_length=15, verbose_name='Status'),
        ),
    ]
