# Generated by Django 5.1.1 on 2024-11-15 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('group', '0007_alter_usergroup_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user_group',
            field=models.ForeignKey(default='62e24575-3873-4760-ab7b-b6eb1e00d502', help_text='The user group to which the attendance record belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_user_group', to='group.usergroup', verbose_name='User Group'),
            preserve_default=False,
        ),
    ]
